import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import TopHeader from "@/components/HomePage/1TopHeader";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  // variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <TopHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
